"use client";
import { useState } from "react";
import { trackEvent } from "./AnalyticsLink";
const encode=(data:Record<string,string>)=>new URLSearchParams(data).toString();
export default function EstimateForm({compact=false}:{compact?:boolean}){
 const [started,setStarted]=useState(false),[submitting,setSubmitting]=useState(false),[success,setSuccess]=useState(false),[errors,setErrors]=useState<Record<string,string>>({});
 function start(){ if(!started){setStarted(true); trackEvent('estimate_form_start');}}
 async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); const form=e.currentTarget; const fd=new FormData(form); const data=Object.fromEntries(fd.entries()) as Record<string,string>; const next:Record<string,string>={}; ['full-name','phone','project-type','location','timeline','contact-method','description','consent'].forEach(k=>{if(!data[k]) next[k]='Required';}); if(Object.keys(next).length){setErrors(next); return;} setSubmitting(true); setErrors({}); try{ await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:encode(data)}); trackEvent('estimate_form_submit'); setSuccess(true); window.history.replaceState(null,'','/thank-you'); }catch{setErrors({form:'Submission failed. Please call or text the business instead.'});}finally{setSubmitting(false);} }
 if(success) return <div className="form-success" role="status"><h2>Thank you — your estimate request was recorded.</h2><p>The next step is a direct conversation about your property, location and project requirements.</p></div>;
 const err=(n:string)=>errors[n]?<span className="field-error" id={`${n}-error`}>{errors[n]}</span>:null;
 return <form id="estimate" className="estimate-form" name="estimate" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/thank-you" onSubmit={submit} onFocus={start} noValidate>
  <input type="hidden" name="form-name" value="estimate"/><p className="hidden"><label>Do not fill this out <input name="bot-field"/></label></p><div className="form-head"><p className="eyebrow"><span/>Request an estimate</p><h2>{compact?'Tell us about the concrete project':'Start with the project details'}</h2><p>No unsupported promises — just the details needed to begin a clear estimate conversation.</p></div>{errors.form&&<p className="form-error">{errors.form}</p>}
  <div className="form-grid"><label>Full name<input name="full-name" autoComplete="name" aria-describedby="full-name-error" required/></label>{err('full-name')}<label>Phone number<input name="phone" type="tel" autoComplete="tel" aria-describedby="phone-error" required/></label>{err('phone')}<label>Email <small>optional</small><input name="email" type="email" autoComplete="email"/></label><label>Project type<select name="project-type" required><option value="">Select one</option><option>Concrete driveway</option><option>Concrete patio</option><option>Concrete slab</option><option>Concrete walkway</option><option>Not sure yet</option></select></label>{err('project-type')}<label>Project city or ZIP<input name="location" required/></label>{err('location')}<label>Approximate timeline<select name="timeline" required><option value="">Select one</option><option>As soon as practical</option><option>Within 1–3 months</option><option>Planning ahead</option><option>Not sure</option></select></label>{err('timeline')}<label>Preferred contact method<select name="contact-method" required><option value="">Select one</option><option>Phone call</option><option>Text message</option><option>Email</option></select></label>{err('contact-method')}<label className="wide">Project description<textarea name="description" rows={5} required placeholder="Tell us the project type, property location, approximate size if known, and anything important about access or photos."/></label>{err('description')}</div><label className="consent"><input type="checkbox" name="consent" value="yes" required/> I agree to be contacted about this concrete estimate request.</label>{err('consent')}<button className="button button-primary" type="submit" disabled={submitting}>{submitting?'Sending…':'Request an Estimate'}</button></form>
}
